GET http://localhost:5134/games
###
GET http://localhost:5134/games/3
###
POST http://localhost:5134/games
Content-Type: application/json

{

    "name": "Street crazytaxi",
    "genreId": 3,
    "price": 19.99,
    "releaseDate": "2023-10-20"

}
###
PUT http://localhost:5134/games/5
Content-Type: application/json

{
    "name":"black mamba",
    "genre":"kobe",
    "price": 2000.454,
    "releaseDate": "2020-01-19"
    
}
###
DELETE http://localhost:5134/games/6
###
GET http://localhost:5134/genres