// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302100245_AddDiaryDb")]
    partial class AddDiaryDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hiking with Nunn",
                            Created = new DateTime(2026, 3, 2, 12, 2, 43, 15, DateTimeKind.Local).AddTicks(4004),
                            Title = "Hiking"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Shopping with Nunn",
                            Created = new DateTime(2026, 3, 2, 12, 2, 43, 15, DateTimeKind.Local).AddTicks(5311),
                            Title = "Shopping"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Diving with Nunn",
                            Created = new DateTime(2026, 3, 2, 12, 2, 43, 15, DateTimeKind.Local).AddTicks(5319),
                            Title = "Diving"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
