GET  http://localhost:5158/playerGames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkthbWF0c29zIiwic3ViIjoiS2FtYXRzb3MiLCJqdGkiOiI4MjM5ZGNlMCIsInJvbGUiOiJhZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUxNTgiLCJodHRwczovL2xvY2FsaG9zdDo3MDY4Il0sIm5iZiI6MTc3Mjc4OTYzMCwiZXhwIjoxNzgwNzM4NDMwLCJpYXQiOjE3NzI3ODk2MzIsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.lpKi95U5kStKTIsOU4SKkyd5xYljx3RxuSc1zRVmxv4
###
GET  http://localhost:5158/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjEiLCJzdWIiOiJwbGF5ZXIxIiwianRpIjoiMjc3YjZjOTAiLCJyb2xlIjoiYWRtaW4iLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MTU4IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzA2OCJdLCJuYmYiOjE3NzI3OTEyNDEsImV4cCI6MTc4MDc0MDA0MSwiaWF0IjoxNzcyNzkxMjQzLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.L1-8qInMe-x49H1wkJtjpfHf3rd9-2UsixUjTA2KVOg