create database TaskManagementAPI;
use TaskManagementAPI;


CREATE TABLE Users (
 Id INT PRIMARY KEY IDENTITY,
 Username NVARCHAR(50) UNIQUE NOT NULL,
 Email NVARCHAR(100) UNIQUE NOT NULL,
 PasswordHash NVARCHAR(255) NOT NULL,
 FirstName NVARCHAR(50),
 LastName NVARCHAR(50),
 CreatedAt DATETIME DEFAULT GETDATE(),
 UpdatedAt DATETIME DEFAULT GETDATE(),
 IsActive BIT DEFAULT 1
);


CREATE TABLE Tasks (
 Id INT PRIMARY KEY IDENTITY,
 Title NVARCHAR(200) NOT NULL,
 Description NVARCHAR(MAX),
 Status NVARCHAR(20) NOT NULL CHECK (Status IN ('Pending', 'InProgress', 'Completed',
'Cancelled')),
 Priority INT NOT NULL CHECK (Priority BETWEEN 1 AND 5),
 UserId INT NOT NULL,
 DueDate DATETIME,
 CreatedAt DATETIME DEFAULT GETDATE(),
 UpdatedAt DATETIME DEFAULT GETDATE(),
 CompletedAt DATETIME,
 FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Categories (
 Id INT PRIMARY KEY IDENTITY,
 Name NVARCHAR(100) UNIQUE NOT NULL,
 Color NVARCHAR(20),
 Icon NVARCHAR(50)
);

CREATE TABLE TaskCategories (
 TaskId INT,
 CategoryId INT,
 PRIMARY KEY (TaskId, CategoryId),
 FOREIGN KEY (TaskId) REFERENCES Tasks(Id) ON DELETE CASCADE,
 FOREIGN KEY (CategoryId) REFERENCES Categories(Id) ON DELETE CASCADE
);

CREATE TABLE Comments (
 Id INT PRIMARY KEY IDENTITY,
 TaskId INT NOT NULL,
 UserId INT NOT NULL,
 Content NVARCHAR(MAX) NOT NULL,
 CreatedAt DATETIME DEFAULT GETDATE(),
 FOREIGN KEY (TaskId) REFERENCES Tasks(Id) ON DELETE CASCADE,
 FOREIGN KEY (UserId) REFERENCES Users(Id)
);

