GET http://localhost:5134/games
###
GET http://localhost:5134/games/1
###
POST http://localhost:5134/games
Content-Type: application/json

{

    "name": "Super Mario",
    "genre": "Playfom",
    "price": 19.99,
    "releaseDate": "2023-10-20"

}
###
PUT http://localhost:5134/games/1
Content-Type: application/json

{
    "name":"black mamba",
    "genre":"kobe",
    "price": 2000.454,
    "releaseDate": "2020-01-19"
    
}
###
DELETE http://localhost:5134/games/1